# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0008_auto_20161024_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_data',
            name='otp',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
