# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0009_auto_20161024_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='access_token_data',
        ),
    ]
