# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city_data',
            old_name='id',
            new_name='city_id',
        ),
        migrations.AddField(
            model_name='city_data',
            name='data_type',
            field=models.IntegerField(default=1),
        ),
    ]
