# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20161219_1758'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_fcm_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=100)),
                ('fcm', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(max_length=100)),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='register.user_data')),
                ('user_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='register.user_data')),
            ],
        ),
    ]
