# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_city_fcm_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_fcm_data',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='city_fcm_data',
            name='user_id',
        ),
    ]
