# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20161013_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 10, 41, 972516, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 10, 44, 129614, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
