# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20170221_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_fcm_data',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='register.user_data'),
        ),
        migrations.AlterField(
            model_name='city_fcm_data',
            name='user_mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='register.user_data'),
        ),
    ]
