# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20170221_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_fcm_data',
            name='city_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city_fcm_data',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='city.city_data'),
        ),
    ]
