# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_auto_20170221_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_fcm_data',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='city_fcm_data',
            name='user_mobile',
        ),
        migrations.AddField(
            model_name='city_fcm_data',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
