# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_auto_20170221_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_fcm_data',
            name='fcm',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
