# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0011_auto_20170609_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydata',
            name='state_name',
            field=models.CharField(choices=[(1, b'Chhatisgarh'), (2, b'Review'), (3, b'Maybe relevant'), (4, b'Relevant'), (5, b'Leading candidate')], default='India', max_length=255),
        ),
    ]
