# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0012_auto_20170609_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydata',
            name='state_name',
            field=models.CharField(choices=[(1, b'Andhra Pradesh'), (2, b'Arunachal Pradesh'), (3, b'Assam'), (4, b'Bihar'), (5, b'Chandigarh'), (6, b'Chhattisgarh'), (7, b'Dadra and Nagar Haveli'), (8, b'Daman and Diu'), (9, b'Delhi'), (10, b'Goa'), (11, b'Gujarat'), (12, b'Haryana'), (13, b'Himachal Pradesh'), (14, b'Jammu and Kashmir'), (15, b'Jharkhand'), (16, b'Karnataka'), (17, b'Kerala'), (18, b'Madhya Pradesh'), (19, b'Maharashtra'), (20, b'Manipur'), (21, b'Meghalaya'), (22, b'Mizoram'), (23, b'Meghalaya'), (24, b'Nagaland'), (25, b'Orissa'), (26, b'Punjab'), (27, b'Pondicherry'), (28, b'Sikkim'), (29, b'Tamil Nadu'), (30, b'Tripura'), (31, b'Uttar Pradesh'), (32, b'Uttarakhand'), (33, b'West Bengal')], default='India', max_length=255),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='name',
            field=models.CharField(choices=[(1, b'Andhra Pradesh'), (2, b'Arunachal Pradesh'), (3, b'Assam'), (4, b'Bihar'), (5, b'Chandigarh'), (6, b'Chhattisgarh'), (7, b'Dadra and Nagar Haveli'), (8, b'Daman and Diu'), (9, b'Delhi'), (10, b'Goa'), (11, b'Gujarat'), (12, b'Haryana'), (13, b'Himachal Pradesh'), (14, b'Jammu and Kashmir'), (15, b'Jharkhand'), (16, b'Karnataka'), (17, b'Kerala'), (18, b'Madhya Pradesh'), (19, b'Maharashtra'), (20, b'Manipur'), (21, b'Meghalaya'), (22, b'Mizoram'), (23, b'Meghalaya'), (24, b'Nagaland'), (25, b'Orissa'), (26, b'Punjab'), (27, b'Pondicherry'), (28, b'Sikkim'), (29, b'Tamil Nadu'), (30, b'Tripura'), (31, b'Uttar Pradesh'), (32, b'Uttarakhand'), (33, b'West Bengal')], default='India', max_length=255),
        ),
    ]
