# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0013_auto_20170609_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydata',
            name='state_name',
            field=models.ForeignKey(db_column='StateData.id', on_delete=django.db.models.deletion.CASCADE, to='city.StateData'),
        ),
        migrations.AlterField(
            model_name='statedata',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
