# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0014_auto_20170609_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydata',
            name='state_id',
        ),
    ]
