# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_data',
            name='otp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
