# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_auto_20161022_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_data',
            name='mobile',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otp_data',
            name='otp',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
