# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_auto_20161022_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_token_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='user_token_data',
        ),
    ]
