# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_auto_20161022_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_token_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 10, 50, 220537, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access_token_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 10, 53, 815665, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 11, 1, 149890, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 11, 6, 538354, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp_data',
            name='mobile',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
