# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20170520_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondata',
            name='subscription_days',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
