# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptiondata_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsubscriptiondata',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
