# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptiondata_subscription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondata',
            name='subscription_description',
            field=models.CharField(default='Subscription Details', max_length=255),
        ),
    ]
