# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=12)),
                ('amount', models.PositiveIntegerField(blank=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
