# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_data',
            name='amount',
            field=models.BigIntegerField(blank=True),
        ),
    ]
