# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20161201_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_data',
            name='amount',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
