# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20161201_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_data',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 12, 12, 14, 34, 606947, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_data',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 12, 12, 14, 44, 35199, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_data',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
