# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offer_data',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('shop_id', models.SmallIntegerField(default=0)),
                ('offer_image', models.CharField(blank=True, max_length=120, null=True)),
                ('category_id', models.SmallIntegerField(default=0)),
                ('data_type', models.SmallIntegerField(default=4)),
                ('offer_descripton', models.CharField(blank=True, max_length=200, null=True)),
                ('offer_code', models.CharField(blank=True, max_length=120, null=True)),
                ('offer_validdate', models.DateTimeField()),
            ],
        ),
    ]
