# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_data',
            name='shop_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
