# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer_data',
            old_name='offer_descripton',
            new_name='offer_des',
        ),
    ]
