# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20161013_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer_data',
            old_name='offer_des',
            new_name='describ',
        ),
        migrations.RenameField(
            model_name='offer_data',
            old_name='offer_code',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='offer_data',
            old_name='offer_image',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='offer_data',
            old_name='offer_validdate',
            new_name='validity',
        ),
        migrations.RemoveField(
            model_name='offer_data',
            name='offer_name',
        ),
    ]
