# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20161023_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_data',
            name='validity',
        ),
    ]
