# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offers_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers_bought',
            name='avialable',
            field=models.BooleanField(default=True),
        ),
    ]
