# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_remove_offer_data_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 10, 45, 990960, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 10, 48, 85208, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
