# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offers_bought_avialable'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers_bought',
            name='offer_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offers_bought',
            name='offer_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='offers_bought',
            name='price',
            field=models.IntegerField(default=-1),
        ),
    ]
