# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20161023_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_data',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
    ]
