# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20161101_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_data',
            name='data_type',
        ),
    ]
