# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_auto_20170607_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdata',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offerdata',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2017, 6, 8)),
        ),
    ]
