# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20170608_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerboughtdata',
            name='avialable',
        ),
        migrations.RemoveField(
            model_name='offerboughtdata',
            name='offer_code',
        ),
        migrations.RemoveField(
            model_name='offerboughtdata',
            name='price',
        ),
        migrations.RemoveField(
            model_name='offerdata',
            name='offer_code',
        ),
        migrations.RemoveField(
            model_name='offerdata',
            name='price',
        ),
    ]
