# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_offer_data_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_data',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
