# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_offer_data_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_data',
            name='offer_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
