# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_offer_data_offer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_data',
            name='image',
            field=models.ImageField(default='/media/offer/default.png', upload_to='offer/'),
        ),
    ]
