# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_auto_20161105_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_data',
            name='category_id',
        ),
    ]
