# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'category', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_data',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_id', models.SmallIntegerField(default=0)),
                ('category_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
