# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_data',
            name='image',
            field=models.ImageField(default='category/default.png', upload_to='category/'),
        ),
    ]
