# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_data',
            name='data_type',
            field=models.SmallIntegerField(default=2),
        ),
    ]
