# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_data_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_data',
            name='city_id',
        ),
        migrations.AddField(
            model_name='category_data',
            name='describ',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category_data',
            name='image',
            field=models.ImageField(default='/media/category/default.png', upload_to='/media/category/'),
        ),
    ]
