# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20161023_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 10, 39, 786922, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
