# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20161105_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_data',
            name='data_type',
        ),
    ]
