# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='mobile',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
