# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(default=0, editable=False)),
                ('category_id', models.IntegerField(default=0, editable=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(default='/media/shop/default.png', upload_to='shop/')),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category_data')),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city_data')),
            ],
        ),
    ]
