# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_data',
            name='password',
            field=models.CharField(default=0, max_length=55),
        ),
    ]
