# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_data',
            name='data_type',
            field=models.SmallIntegerField(default=3),
        ),
    ]
