# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_data_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_data',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shop_data',
            name='describ',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
