# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20161023_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_data',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shop_data',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
