# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20161023_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_data',
            old_name='describ',
            new_name='description',
        ),
        migrations.AddField(
            model_name='shop_data',
            name='shop_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
