# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20161025_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop_data',
            old_name='shop_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='shop_data',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shop_data',
            name='data_type',
        ),
    ]
