# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170606_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdata',
            name='latitude',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shopdata',
            name='longitude',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='subscription_expiry_date',
            field=models.DateTimeField(default=datetime.date(2017, 6, 7)),
        ),
    ]
