# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170608_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='subscription_expiry_date',
            field=models.DateTimeField(default=datetime.date(2017, 6, 9)),
        ),
    ]
