# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170610_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdata',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='subscription_expiry_date',
            field=models.DateTimeField(default=datetime.date(2017, 6, 13)),
        ),
    ]
