# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170612_1929'),
        ('shop', '0018_auto_20170613_1206'),
    ]

    operations = [
    ]
