# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_data',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(blank=True, max_length=120, null=True)),
                ('message', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
