# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_data',
            name='image_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
