# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20161013_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_data',
            name='image_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
