# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_remove_image_data_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 11, 29, 975133, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 11, 32, 62227, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
