# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoffers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_bought_data',
            name='offer_id',
            field=models.IntegerField(default=0),
        ),
    ]
