# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.SmallIntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
