# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20161022_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='mobile',
            field=models.PositiveSmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
