# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20161022_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 11, 9, 562036, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 11, 17, 143397, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_data',
            name='mobile',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
