# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20161105_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
