# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0002_auto_20161012_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='version_control',
            new_name='version_data',
        ),
    ]
