# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0004_version_data_ver_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcm_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
