# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0005_fcm_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version_data',
            name='ver_type',
        ),
    ]
