# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0006_remove_version_data_ver_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='version_data',
            name='ver_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
