# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0007_version_data_ver_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcm_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 11, 22, 685566, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcm_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 11, 24, 477112, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version_data',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 23, 11, 11, 26, 295690, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version_data',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 23, 11, 11, 28, 61979, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
